# Generated by Django 5.2.3 on 2025-06-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_restaurant_image_restaurant_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
